### ISSUE TITLE
Batch events in single email

### ISSUE THREAD

**Issue by Odraio** [datalust/seq-apps#114]
The [Seq-App-DigestEmail](https://github.com/datalust/seq-app-digestemail) didn't have any updates for years. 
I was wondering if there are plans to implement/ port the batch functionality in [Seq.App.EmailPlus]?

E.g. https://github.com/datalust/seq-app-digestemail/blob/dev/src/Seq.App.DigestEmail/DigestEmailReactor.cs contains a basic batch implementation (which works great!) using a timer and 'waiting' list.

**Comment by nblumhardt** [comment]
Thanks for getting in touch. I'm following up via https://github.com/datalust/seq-tickets/discussions/2212.
