### ISSUE TITLE
Feature Request: Email Plus SMTP Configuration

### ISSUE THREAD

**Issue by RyKilleen** [datalust/seq-apps#12]
First of all, just want to say that Seq has been an absolutely incredible product to work with all around. It's made life incredibly easy on us.

On our current server, we use SMTP with the `SmtpClient.SmtpDeliveryMethod` set to  `SpecifiedPickupDirectory`. I thought a possible enhancement would include the ability to configure Email Plus in a similar matter, for circumstances like ours (rare as it might be.)

I'd be happy to dive in and do a PR for it, this would be my first foray into something of this nature and I might need a little help to get the proper tests in place.

Thanks for an awesome product!

**Comment by RyKilleen** [comment]
(I'd be happy to dive in and do a PR for it, this would be my first foray into something of this nature and I might need a little help to get the proper tests in place.)

**Comment by nblumhardt** [comment]
Closing this one as stale; sorry we weren't able to move this forward, but thanks again, and Happy New Year :-)
