### ISSUE TITLE
Anomaly Detection in Addition to Threshold?

### ISSUE THREAD

**Issue by normanhh3** [datalust/seq-apps#20]
Hi Folks,

Has anyone considered using something like this https://github.com/twitter/AnomalyDetection to do anomaly detection on an event stream?

Seems like a match made in Heaven if it weren't for the fact that the algorithm was implemented in R and either needs to be marshaled across process boundaries or converted to C#.

Anyway, I'm considering switching to Seq for monitoring on the backend and am excited by what I see you all have put together.

**Comment by nblumhardt** [comment]
Hi Norman - thanks for the link, it looks like an excellent piece of software.

I haven't seen anything like this, but the Rx ecosystem might yield some of this kind of functionality in .NET..? An initial search didn't turn up any obvious hits - it'd be great to hear of anything you encounter that might be easier to integrate.

**Comment by normanhh3** [comment]
Yeah, I looked at the R code yesterday to see how hard it might be to
implement the algorithm. It would take learning more R for sure! Ha ha.

Seq Apps look totally awesome by the way! If I get something implemented I
will be sure to share. :-)
