### ISSUE TITLE
Question: Can a Seq App modify an API key specific filter?

### ISSUE THREAD

**Issue by normanhh3** [datalust/seq-apps#23]
Here is my scenario:

Version A of software is released, an exception starts cropping up in, it is going to be 2 weeks to fix the issue, I want to silence the noise until that issue can be addressed.  I would love to be able to send that exception entry and using the hash of the event silence further events that are associated to that specific version of the software.   We deploy version B of the software, and now if that same exception pops up, the filter won't find it because the filter was created for the previous event's "signature".

The key thing I need to know, is there a way that I can modify the filter that is associated to incoming events for a specific API key via a Seq App?

If so, I really have all I need to implement this app.

Ideally it would be great if the app would clean up those filters that are now "out-of-date".  Are there maintenance hooks that Seq Apps can hook into?

Thanks for any pointers and feedback!

**Comment by nblumhardt** [comment]
Hi Norman,

It's a little bit round-about, but the app should be able to call back into the API to do this, using https://github.com/datalust/seq-api. Does this sound feasible?

Cheers,
Nick

**Comment by normanhh3** [comment]
That sounds like it would be a good start point.

This looks like the [right place (ApiKeyEntity)](https://github.com/datalust/seq-api/blob/master/src/Seq.Api/Api/Model/Inputs/ApiKeyEntity.cs) to modify the InputFilter.

It looks like the Seq App is going to have to authenticate to the Seq API.  I'm currently setup with AD auth and I'm not fond of putting a rolling username/pw combo into the Seq App Instance configuration.  Any thoughts on how to cross that bridge?

**Comment by nblumhardt** [comment]
Ah, that's interesting - I will need to give this one a bit more thought. I think, as it stands, authenticating with username/password would be the only way to achieve this.

Ideally, the app would be provided programmatically with an already-authenticated API client... Looking into that possibility.

**Comment by nblumhardt** [comment]
@normanhh3 the new versions of the Seq API client support AD login - does this help? It should be possible to add the account that Seq itself is running under as a user in Seq.

**Comment by normanhh3** [comment]
Sounds like a perfect solution!
