### ISSUE TITLE
Be able to setup FileArchiver to run before retention hits the database and not run per event

### ISSUE THREAD

**Issue by cilerler** [datalust/seq-apps#25]
In order to eliminate double logging I would like to be able to run FileArchiver as a archiver and not second data recorder.  I mean retention system should be able to trigger FileArchiver to backup the events that will be wiped out.

**Comment by nblumhardt** [comment]
Hi @cilerler - thanks for this note, I gave some thought to how this might be done, but it seems I never managed to follow up via the ticket. Sorry about that!

Implementing this would require a substantial overhaul of the Seq retention processing system, which is unlikely in the near future (it's very perf-sensitive so takes time to change).

I'll close this as I think the "eager" archiving is a workable option for now, but I'll definitely keep the possibility of doing this upon deletion in mind.

Thanks again, and sorry again for the slow response!

Nick

**Comment by cilerler** [comment]
Thank you for the update @nblumhardt
