### ISSUE TITLE
EmailPlus : make EventType compatible with querystring

### ISSUE THREAD

**Issue by tbolon** [datalust/seq-apps#26]
Currently in EmailPlus, the `{{$EventType}}` property uses $ + X8 format (`$06EF5A34`). See [EmailReactor.cs#L144](https://github.com/datalust/seq-apps/blob/master/src/Seq.App.EmailPlus/EmailReactor.cs#L144)

It is not compatible with the url querystring format (it expects `0x06EF5A34`).

The consequence is that we can't create a link which open seq filtered with all the events for this EventType.

Can we change the format of the value ? Or create another property with a correct format if backward compatibility is an issue ?

**Comment by nblumhardt** [comment]
Hi Thomas; Seq still accepts the `$1234abcd` format, so URLs like the one below should work:

```
http://localhost:5341/#/events?filter=$1234abcd
```

Is it possible you're attempting to compare the value with `@EventType`, which does require the new syntax?

**Comment by tbolon** [comment]
You are right, I was trying to use the `@EventType = 0x...` syntax, because I copied the url provided in the default template for the Id property.

You can ignore this issue and close it, thanks !

**Comment by nblumhardt** [comment]
Great 👍
