### ISSUE TITLE
Email+ does not have Base Seq Url property

### ISSUE THREAD

**Issue by alexeyzimarev** [datalust/seq-apps#27]
We get all emails fromt he app with `localhost` event url. Another apps like Slack notification app, have the Seq base url setting, which works great. Suggestion is to implement the same in Email+.

**Comment by nblumhardt** [comment]
Hi Alexy, thanks very much for the note.

The email app should use the first URL listed in the _listenUris_ section of _Seq.json_. The apps with a base URL setting generally pre-date the existence of the first-class property handed through from Seq.

There are some details on the JSON configuration format here: http://docs.getseq.net/docs/json-config - please let me know if you need further help with it.
