### ISSUE TITLE
Email+ can't use Handlebarsjs Raw to prevent escaping

### ISSUE THREAD

**Issue by csmarvz** [datalust/seq-apps#28]
Hello guys,
I'm trying now to send a message with `<br/>` in it but it fails :(
The body template is
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">`
<head>
</head>
<body>
  \{{$Message}}
</body>
</html>
```

in {{$Message}} I have something like `"Hello<br/>world"`
The result is simply \ followed by the escaped message.

source for the syntax: https://handlebarsjs.com/expressions.html

**Comment by nblumhardt** [comment]
Thanks for the note @csmarvz. The app uses [Handlebars.Net](https://github.com/rexm/Handlebars.Net) for  templating - it's possible there might be some differences with the original JavaScript version. I'll have to look into it; if you have a chance to check out Handlebars.Net, any help/suggestions would be appreciated.

**Comment by csmarvz** [comment]
ah damn I didn't see this detail!!! And indeed, it's not implemented yet
https://github.com/rexm/Handlebars.Net/issues/179

**Comment by nblumhardt** [comment]
Ah, I see - thanks for the follow-up, will keep an eye on that ticket 👍

**Comment by nblumhardt** [comment]
Hi @csmarvz - I just re-read this and realised that the linked ticket is for `{{{{` raw helpers, not for `{{{` raw escaping. Handlebars.net and the email app support raw output today with the triple-stash `{{{Something}}}` syntax.

Let me know if this works for you! :-)
