### ISSUE TITLE
System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by stevescc** [datalust/seq-apps#29]
Hi

[Similar to this issue](https://github.com/datalust/seq-apps/issues/18) I'm getting the following exception when I try to load my seq app (as shown in C:\ProgramData\Seq\Logs).

> System.MissingMethodException: Method not found

Is there anywhere we can see which versions of Seq and Serilog match up so that we don't receive this issue? I'm finding it hard to know when I should or shouldn't be seeing this error.

Our Seq version is Seq 3.2.16.

My SeqApp is:

- .NET 4.5 (aside: can I use higher?)
- Seq.Apps 3.4.17
- Serilog 2.0.0

(I don't include these in the nuget package).

**Comment by nblumhardt** [comment]
Hi @stevescc,

On the .NET version, yes, you can target the .NET Framework version that's running on the Seq host machine. (4.5 is always a safe bet, but I think most Seq instances end up running on 4.6 or later.)
I 
Nothing in your list of dependencies above looks problematic. Is it possible to collect the complete exception message? When I've hit this error, it normally includes the name of the missing method - along with the exception stack trace, this should help us narrow down possible culprits pretty quickly.

**Comment by stevescc** [comment]
Hi @nblumhardt 

Thanks for your help so far.

Looks to be the ILogger.Error message in Serilog. Here is the complete exception message:

> 2017-04-12 22:02:58.167 +00:00 [Error] Failed to load "ToLogsApiEventHub"
> System.MissingMethodException: Method not found: 'Void Serilog.ILogger.Error(System.String)'.
>    at Seq.App.EventHubs.EventHubReactor.OnAttached()
>    at Seq.Server.Features.Runner.AppHost..ctor(ILogger logger, Func`2 createReactorInstance, HostedApp hostedApp, AppInstance appInstance, AppHostSettings settings)
>    at Seq.Server.Features.Runner.AppHost..ctor(IInternalEventPublisher publisher, HostedApp hostedApp, AppInstance appInstance, AppHostSettings settings)
>    at Seq.Server.Features.Runner.SandboxedAppContainer.Initialize(IInternalEventPublisher publisher, String hostedApp, String appInstance, AppHostSettings settings)
>    at Seq.Server.Features.Runner.SandboxedAppContainer.Initialize(IInternalEventPublisher publisher, String hostedApp, String appInstance, AppHostSettings settings)
>    at Seq.Server.Features.Runner.RunningApp.LoadSandboxedAppContainer(AppDomain domain, HostedApp app)
>    at Seq.Server.Features.Runner.RunningApp.Run()

**Comment by nblumhardt** [comment]
Thanks for the follow-up. Seq 3.2 pre-dates Serilog 2.0 (hard to believe!), so internally your server will be loading up Serilog 1.5.

You can rebuild your app against the older Serilog version and everything should just work, but there are a bunch of improvements between 3.2 and the current 3.4 that you'd probably enjoy if you choose to upgrade the server instead. If you decide to upgrade, make sure to check out "Upgrading" in [the 3.3 release notes](http://blog.getseq.net/seq-3-3-is-here-2/) for some more info.

**Comment by stevescc** [comment]
Thanks again @nblumhardt 
Ok. I wasn't sure what version of Serilog comes with Seq.
The upgrade path was very smooth so we've updated the server (and our Seq.Apps).

**Comment by nblumhardt** [comment]
Awesome, thanks Steve.
