### ISSUE TITLE
The new default template does not render properly in Outlook 2013

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-apps#38]
As of Seq v4.0.60 with Email+ v2.0.60 , using the "default" template, the emails I get do not look like what they should in Outlook 2013.

Expected something like : https://blog.getseq.net/content/images/2017/05/Alerts-Email.png (from blog post at https://blog.getseq.net/hello-seq-4-0-dashboards-alerts-more-improvements/) ...

But I get : 

![image](https://cloud.githubusercontent.com/assets/160544/26400844/45418c5e-4083-11e7-8b2c-0d3b5b139288.png)

i.e. the header seems to be missing.

When I open the source in a browser, it does seem to display well : 
![image](https://cloud.githubusercontent.com/assets/160544/26400928/a8852992-4083-11e7-8fdc-0290a36bd5fb.png)

**Comment by tsimbalar** [comment]
I'm not quite sure about the css support in Outlook, but tweaking a bit the html in the emails, and playing around (with extension http://outlookhtmleditor.codeplex.com/ ) , I have the feeling that Outlook does not support multiple classes on the same html element, and this is confirmed here: 

http://existdissolve.com/2010/08/emails-in-outlook-2010-ugh/

> Pick a Class, Any Class…But Only One!
> 
> For any normal rendering engine, you can easily apply multiple classes to HTML elements, allowing for a really nice level of specificity. Outlook 2010? Not a chance. You can specify one class, and one class only; the first in your “list” will be acknowledged, and the rest will be ignored. Not a huge deal, but something of a pain if you have complicated email stylesheets and a lot of code to wade through…


And this is therefore a problem for the parts of the template that look like this :  `class="seq-event-header error"`
```
{{#if_eq $Level "Fatal"}}
<div class="seq-event-header error">
{{/if_eq}}
{{#if_eq $Level "Error"}}
<div class="seq-event-header error">
{{/if_eq}}
{{#if_eq $Level "Warning"}}
<div class="seq-event-header warning">
{{/if_eq}}
{{#if_eq $Level "Information"}}
<div class="seq-event-header information">
{{/if_eq}}
{{#if_eq $Level "Debug"}}
<div class="seq-event-header debug">
{{/if_eq}}
{{#if_eq $Level "Verbose"}}
<div class="seq-event-header debug">
{{/if_eq}}
```

playing around, I can confirm that this works, for instance for an error : 
**css** : 
```
.seq-event-header-error {
            color: #fff;
            padding: 20px 40px;
        }
            .seq-event-header-error {
                background-color: #e03836;
            }
```
**html** : 
`<div class="seq-event-header-error">`

obviously that makes the css a bit less elegant ... but I guess "elegant" is pretty subjective when designing email templates :)

Another option would be to generate markup like this : 
```
<div class="seq-event-header">  
	<div class="error">
		<div class="seq-event-level">{{$Level}}</div>
		<div class="seq-event-timestamp" title="{{$UtcTimestamp}}">{{$LocalTimestamp}}</div>
	</div>			
</div>            

```

and updating the css like so (i.e. replacing the "double class selectors" with descendant selectors) : 

```
.seq-event-header {
    color: #fff;
    padding: 20px 40px;
}
    .seq-event-header .error {
        background-color: #e03836;
    }
    .seq-event-header .warning {
        background-color: #f9c019;
    }
    .seq-event-header .information {
        background-color: #0098ff;
    }
    .seq-event-header .debug {
        background-color: #aaa;
    }
    .seq-event-header .seq-event-level {
        font-size: 32px;
        line-height: 40px;
        font-weight: bold;
    }

```

**Comment by tsimbalar** [comment]
I've created a pull request to try and fix this issue.

**Comment by laurencee** [comment]
This probably affects all versions of Outlook and Exchange Webmail.

**Comment by nblumhardt** [comment]
Thanks @laurencee - we should have @tsimbalar 's fix out later this week 👍

**Comment by nblumhardt** [comment]
Alrighty, think I'm nearly there!

![image](https://cloud.githubusercontent.com/assets/342712/26665630/5bf0f140-46de-11e7-9bab-2e1682600456.png)

Unfortunately, @tsimbalar, I've had to change the approach a bit and will have to open a new PR with these changes. I'm down to crafting styles manually (getting the inliner out of the equation) and using table-based layouts. Eeek!

...but, it looks much better. PR incoming!

**Comment by tsimbalar** [comment]
gotta love designing html emails 🙄
