### ISSUE TITLE
Seq.App.EmailPlus $ServerUri variable shows as localhost

### ISSUE THREAD

**Issue by SeanKilleen** [datalust/seq-apps#45]
Hi all,

I am using the `Seq.App.EmailPlus` app (fantastic by the way, thanks!)

We have multiple Seq environments (eg. http://server1:5341 and http://server2:5341).

However, every e-mail that comes from each of those environments uses a link of `http://localhost:5341`, which doesn't allow us to actually link to the events.

It appears as though `$ServerUri` in `DefaultBodyTemplate.html` is set to `localhost` and I can't see a way to change it.

Is there a place to set this variable within the Seq config that I'm not seeing? 

Please advise. Thanks!

**Comment by nblumhardt** [comment]
Hi Sean,

Each server will report the _first_ URI listed in its configuration. Try:

```
seq config -k api.listenUris
```

This should print something like:

```
http://localhost:5341/
```

To report something more specific, try:

```
seq config -k api.listenUris -v http://server1:5341,http://localhost:5341
seq restart
```

Let me know if that doesn't sort it out. Cheers!

**Comment by SeanKilleen** [comment]
Hi Nick, 

This looks like it did exactly what I needed; thanks! 👍 Closing this out.

**Comment by nblumhardt** [comment]
Great, thanks for closing the loop 👍
