### ISSUE TITLE
EmailPlus - Multi-line properties don't render properly in Outlook 2013

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-apps#46]
At least in my case, with Outlook 2013, properties that contain multiple lines do not render on multiple lines in the email  (this is also true about the *Rendered message* in bold) :

![image](https://user-images.githubusercontent.com/160544/31599278-fbe79bac-b251-11e7-877c-3924c7effa24.png)

The initial message in Seq looks like this : 
![image](https://user-images.githubusercontent.com/160544/31599314-24a6932c-b252-11e7-9954-52d28af900c5.png)

**Comment by tsimbalar** [comment]
FWIW, it seems that 
```css
white-space:pre-wrap;
```
like in https://github.com/datalust/seq-apps/blob/1cb6a5f9ec682afaf6a4b34815a99a470f0beeb5/src/Seq.App.EmailPlus/Resources/DefaultBodyTemplate.html#L104 is not supported in Outlook

see https://www.campaignmonitor.com/css/text-fonts/white-space/ 

Just using 
```css
white-space:pre;
```

seems to work better

**Comment by tsimbalar** [comment]
If I take the contents from https://github.com/datalust/seq-apps/blob/1cb6a5f9ec682afaf6a4b34815a99a470f0beeb5/src/Seq.App.EmailPlus/Resources/DefaultBodyTemplate.html and replace `pre-wrap;` with  `pre;` all over the place, it looks nicer, and gives the following:

![image](https://user-images.githubusercontent.com/160544/31599856-6ef6915a-b254-11e7-93ab-25550149a073.png)

which is better, and looks closer to the Seq layout :)

**Comment by nblumhardt** [comment]
Thanks for the report, Thibaud.

I wonder if including both, e.g. `white-space: pre; white-space: pre-wrap;` might suit Outlook better, but still trigger `pre-wrap` where it's supported?

I recall `pre` looking rough when the lines are too wide for the viewport - scrollbars can be ugly in browser clients, but hiding them makes it difficult to read long lines that overflow.

**Comment by tsimbalar** [comment]
I gave it a try, replacing occurrences of 
```css
white-space:pre-wrap;
```

with 

```css
white-space:pre;
white-space:pre-wrap;
```

seems to do the job for Outlook 2013, multi-line properties are honored (but no change to the Rendered Message, which is a similar behavior to Seq) :
![image](https://user-images.githubusercontent.com/160544/31705665-a0320586-b3e6-11e7-9153-6ddafb3ace8a.png)

I'll update my PR

**Comment by nblumhardt** [comment]
Thanks for investigating! Build should be coming through CI shortly 👍
