### ISSUE TITLE
Seq.App.Replication - Support for Active/Active

### ISSUE THREAD

**Issue by ApoelAlex** [datalust/seq-apps#54]
Hi there,

It would be nice to have two running instances of Seq in Active/Active mode.

We are about to deploy a big project and we choose Seq for our logs. The Seq instances will be sitting on different servers and will be accessed using a Load Balancer.

So requirement is that the two servers will be sending the logs to each other and no duplication of requests will occurred. 

An easy way to do it, is to enrich the Replication Logger with a property (to mark that the specific event is because of replication process) and each Replication Logger will skip all events that where created due to replication purposes.

**Comment by nblumhardt** [comment]
Hi, thanks for the note!

This can be achieved today, using API keys - on each server, an API key can be set up for the other server to send logs through. These API keys can attach properties to the incoming events like `Origin = 'Server1'`, and then the replication apps can be fed with signals like `Origin <> 'Server1'`.

If you need some more help or info please let me know.

Best regards,
Nick
