### ISSUE TITLE
EmailPlus - Support Templates in 'To' Property of EmailReactor

### ISSUE THREAD

**Issue by jwhitex** [datalust/seq-apps#58]
I would like to propose adding support for sending emails to recipients specified in a context object of a seq log.

Implementation would involve adding a backing field to the `To` property and assigning it in a manner similar to how [`SubjectTemplate`](https://github.com/datalust/seq-apps/blob/36d69428a3167baad0c0353417782e4da7fce36e/src/Seq.App.EmailPlus/EmailReactor.cs#L58)'s backing field is [assigned](https://github.com/datalust/seq-apps/blob/36d69428a3167baad0c0353417782e4da7fce36e/src/Seq.App.EmailPlus/EmailReactor.cs#L33) in the constructor of `EmailReactor`.

Thoughts?

**Comment by nblumhardt** [comment]
Thanks for the note, Jacob.

I have a feeling this discussion has come up before, though I can't track the thread down :-) .. It seems like a reasonable enhancement to make, but needs some thinking through at our end.

Would the scenario still be essentially alerting, for you? I'm unsure about the email app's suitability as a generic email templating mechanism, since reliably delivering large numbers of emails on behalf of an application could stretch the implementation in unintended ways.

Thanks!

**Comment by jwhitex** [comment]
Thanks for considering this! The use case I am attempting to cover is one that occurs only under exceptional circumstances (implies alert). Both a user and I will receive an email because it implies work for me and they'd like to know about it.

The main benefit of this feature is its' minimizing effect on maintenance of email filters as the number of candidates for email notifications grow. In my use case the number of candidates is a small subset of total users. 

I see now that adding this 'opens the box' when it comes to possible use cases for Email+. To prevent abuse it may be wise to add a note to the documentation implying intended use. Something like: "Would Email+ be executed given the non faulty operation of your system that relies on it?". This along with additional statements could help stave off open issues resulting from misuse.

**Comment by nblumhardt** [comment]
Thanks for the follow-up! :+1:

It's a tough one - it's somewhat borderline as although I'm sure others would put this to use, there's still runtime cost and complexity thanks to compiling another template per email that might not be justified for most uses.

Is forking this repo and deploying a modified copy an option for the time being?

**Comment by jwhitex** [comment]
I'm a bit adverse to the idea given the continual effort in maintaining one (setting up ci etc. 🔢 ), but perhaps that's the way to go.

I haven't looked into it but a way around always compiling a template could be to put a checkbox on the plugin page under the 'To' field and let this indicate whether to compile a template for the field or take the value as given. 

Anyways, thanks for your feedback!

**Comment by nblumhardt** [comment]
Hi @jwhitex - we've since had some more feedback on this and it seems like it would be more widely used than I anticipated; reopening, not sure when we'll be able to schedule the work in but it shouldn't be too complicated 👍 Thanks again!

**Comment by nblumhardt** [comment]
This is out in 2.0.87. Cheers!
