### ISSUE TITLE
Include Last Log Event and Parameters with Threshold Breached Event

### ISSUE THREAD

**Issue by bbrandt** [datalust/seq-apps#9]
I feel that this would make the notifications produced by a signal of threshold events a bit more useful.  

Would we need to put the parsed text of the original event into a parameter of the threshold event to avoid changing the threshold event message text?

Will any of the planned features for Aggregate Queries in Seq make the Threshold app obsolete?  The part I'm most unsure of is if Aggregate Queries will be able to feed signals that could then become notifications.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, I'll give this some thought.

Having "online query" support driven by aggregate queries would be absolutely fantastic for notifications, but it won't be available in the first cut of the feature. Some very interesting possibilities here however!

**Comment by nblumhardt** [comment]
I think this ticket is obsoleted by the new alerts system. Thanks again for the suggestion, hope all is well in your neck of the woods, Ben.

Nick
